name: Flutter CI/CD  
  
on:  
  push:  
    tags:  
      - 'v*' # 只对以 'v' 开头的 tag 触发构建  
  
jobs:  
  build-and-release:  
    name: Build and Release  
    runs-on: macos-latest # macOS 用于构建 iOS 应用  
  
    steps:  
      - uses: actions/checkout@v2  
  
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.2'
  
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.yaml') }}
  
      - name: Get packages
        run: flutter pub get
  
      - name: Run tests
        run: flutter test
   
      - name: Build Android APK  
        run: flutter build apk --release  
  
      - name: Build Android App Bundle (AAB)  
        run: flutter build appbundle --release  
  
      - name: Build iOS IPA  
        run: |  
          # 配置 Xcode 版本，这里使用的是默认的最新稳定版  
          sudo xcode-select --reset  
          # 构建 iOS 应用  
          flutter build ios --release --no-codesign  
          # 找到并压缩生成的 IPA 文件  
          find . -name "*.ipa" -type f -exec zip -r {}.zip {} \;  
   
      - name: Create Release  
        id: create_release  
        uses: actions/create-release@v1  
        env:  
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
        with:  
          tag_name: ${{ steps.get_version.outputs.VERSION }}  
          release_name: Release ${{ steps.get_version.outputs.VERSION }}  
          draft: false  
          prerelease: false  
  
      - name: Upload Android APK to Release  
        id: upload-apk-release-asset  
        uses: actions/upload-release-asset@v1  
        env:  
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
        with:  
          upload_url: ${{ steps.create_release.outputs.upload_url }}  
          asset_path: ./build/app/outputs/apk/release/app-release.apk  
          asset_name: app-release.apk  
          asset_content_type: application/vnd.android.package-archive  
  
      - name: Upload Android App Bundle (AAB) to Release  
        id: upload-aab-release-asset  
        uses: actions/upload-release-asset@v1  
        env:  
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
        with:  
          upload_url: ${{ steps.create_release.outputs.upload_url }}  
          asset_path: ./build/app/outputs/bundle/release/app-release.aab  
          asset_name: app-release.aab  
          asset_content_type: application/octet-stream  
  
      - name: Upload iOS IPA to Release  
        id: upload-ipa-release-asset  
        uses: actions/upload-release-asset@v1  
        env:  
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
        with:  
          upload_url: ${{ steps.create_release.outputs.upload_url }}  
          asset_path: ./*.ipa.zip  
          asset_name: app.ipa.zip  
          asset_content_type: application/zip