name: Flutter CI  
  
on:  
  push:  
    tags:  
      - 'v*' # Trigger on version tags like v1.0.0  
  
jobs:  
  create_release:
    name: Create Release  
    runs-on: ubuntu-latest  
    steps:  
      # 提取版本号
      - name: Extract version from tag  
        run: |  
          VERSION=${GITHUB_REF#refs/tags/}  
          echo "VERSION=$VERSION" >> $GITHUB_ENV      

      #创建release
      - name: Create Release  
        id: create_release  
        uses: actions/create-release@v1  
        env:  
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
        with:  
          tag_name: ${{ env.VERSION }}  
          release_name: Release ${{ env.VERSION }}  
          draft: false  
          prerelease: false
    outputs:  
      result_url: ${{ steps.create_release.outputs.upload_url }}          
      result_version: ${{ env.VERSION }}          

  update_windows_version:
    name: Update Windows exe version
    needs: [create_release] 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      #- run: npm ci
      # or one-off:
      #- run: npm install execa
      - uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const path = './install/builderWindowsExe.iss';
            let scriptContent = fs.readFileSync(path, 'utf8');
            scriptContent = scriptContent.replace(/AppVersion=.*$/m, `AppVersion=${{ needs.create_release.outputs.result_version }}.substring(1)`);
            fs.writeFileSync(path, scriptContent);


  build_android:  
    name: Build Android  
    needs: [create_release]  
    runs-on: ubuntu-latest  
    steps:  
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Flutter 
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.2'
          channel: 'stable'

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.yaml') }}
  
      - name: Get packages
        run: flutter pub get
  
      - name: Run tests
        run: flutter test    

      - name: Build APK and AAB  
        run: |  
          flutter clean  
          flutter build apk
          flutter build appbundle

      - name: Upload Android APK to Release  
        id: upload-apk-release-asset  
        uses: actions/upload-release-asset@v1
        env:  
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
        with:  
          upload_url: ${{ needs.create_release.outputs.result_url }}  
          asset_path: ./build/app/outputs/flutter-apk/app-release.apk    
          asset_name: app-release-${{ needs.create_release.outputs.result_version }}.apk  
          asset_content_type: application/vnd.android.package-archive  
    
      - name: Upload Android App Bundle (AAB) to Release  
        id: upload-aab-release-asset  
        uses: actions/upload-release-asset@v1  
        env:  
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
        with:  
          upload_url: ${{ needs.create_release.outputs.result_url }}  
          asset_path: ./build/app/outputs/bundle/release/app-release.aab  
          asset_name: app-release-${{ needs.create_release.outputs.result_version }}.aab  
          asset_content_type: application/octet-stream  
   
  build_ios:  
    name: Build iOS  
    needs: [create_release]  
    runs-on: macos-latest  
    steps:  
      - name: Checkout Code
        uses: actions/checkout@v4  

      - name: Set up Flutter 
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.2'
          channel: 'stable'

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.yaml') }}
  
      - name: Get packages
        run: flutter pub get
  
      - name: Run tests
        run: flutter test    

      - name: Build iOS app  
        run: |  
          flutter clean  
          flutter build ios --release --no-codesign 

      - name: Create IOS Release Artifacts  
        run: |  
          mkdir artifacts  
          cp -r build/ios/iphoneos/Runner.app artifacts/Runner.app  
          zip -r artifacts/Runner.ipa artifacts/Runner.app  
   
      - name: Upload iOS IPA to Release  
        id: upload-ipa-release-asset  
        uses: actions/upload-release-asset@v1  
        env:  
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
        with:  
          upload_url: ${{ needs.create_release.outputs.result_url }}  
          asset_path: ./artifacts/Runner.ipa  
          asset_name: ios-runner-${{ needs.create_release.outputs.result_version }}.ipa
          asset_content_type: application/zip
            
  build_windows:  
    name: Build Windows  
    needs: [update_windows_version]  
    runs-on: windows-latest  
    steps:  
      - uses: actions/checkout@v4  

       # 安装 Inno Setup 编译器
      - name: Download Inno Setup
        run: |
          Invoke-WebRequest -Uri 'https://files.jrsoftware.org/is/6/innosetup-6.2.2.exe' -OutFile 'innosetup-6.2.2.exe'
     
      - name: Install Inno Setup
        run: |
          Start-Process -FilePath 'innosetup-6.2.2.exe' -ArgumentList '/SILENT' -Wait
     
     # 运行 Inno Setup 编译器命令，例如打印版本号
     # - name: Check Inno Setup version
     #   run: iscc /V

      - name: Set up Flutter 
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.2'
          channel: 'stable'

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.yaml') }}
  
      - name: Get packages
        run: flutter pub get
  
      - name: Run tests
        run: flutter test    

      - name: Build Windows app  
        run: flutter build windows  

      - name: Inno Setup
        run: iscc /Q /OOutputLog.txt install/builderWindowsExe.iss  
 
      - name: Upload Windows exe to Release  
        id: upload-exe-release-asset  
        uses: actions/upload-release-asset@v1  
        env:  
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
        with:  
          upload_url: ${{ needs.create_release.outputs.result_url }}  
          asset_path: ./build/windows/install/*
          asset_name: windows-${{ needs.create_release.outputs.result_version }}.exe
          asset_content_type: application/octet-stream 
            
  

    